name: CI

on:
  pull_request:

jobs:
  ci:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          # TODO: change this into configuration variable.
          version: "0.5.7"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # To be seen if other tests should be added
        run: uv run pytest tests

      - name: Run ruff checks
        run: uv run ruff check

      - name: Run ruff formatting
        run: uv run ruff format --check
